### ISSUE TITLE
Misleading error with BotServiceConnector: req.on is not a function

### ISSUE THREAD

**Issue by juhamust** [microsoft/BotBuilder-Azure#10]
I'm developing a bot in Azure using functions. While testing the API with Postman following error is raised.
```
2017-03-14T12:52:04.234 Exception while executing function: Functions.messages. mscorlib: TypeError: req.on is not a function
    at D:\home\site\wwwroot\node_modules\botbuilder\lib\bots\ChatConnector.js:46:21
    at D:\home\site\wwwroot\node_modules\botbuilder-azure\lib\BotServiceConnector.js:17:13
    at handler (D:\home\site\wwwroot\messages\index.js:160:10)
    at D:\Program Files (x86)\SiteExtensions\Functions\1.0.10774\bin\azurefunctions\functions.js:93:24.
```
After looking into sources (https://github.com/Microsoft/BotBuilder/blob/master/Node/core/lib/bots/ChatConnector.js#L41) it was noticed how body is required in POST or otherwise ChatConnector expects `req` to have `on` method which does not exist.

Perhaps something to improve in ChatConnector or BotServiceConnector? Dummy methods, perhaps?

**Comment by juhamust** [comment]
And now the function is returning 200, but no response is shown in any of the bot clients (tested with Bot Emulator and Web component). Requests are coming but no error is shown. I wonder where to continue from here?

**Comment by rcarmo** [comment]
I'm having the same issue when trying to pass the request to the connector:

```
Exception while executing function: Functions.bot. mscorlib: TypeError: req.on is not a function
```

Am going through existing samples to figure out what is going on, but to no avail so far.

**Comment by cleemullins** [comment]
Thank you for opening an issue against the BotBuilder-Azure repo. As part of the Bot Framework v4 release, we’ve moved all the Azure related work to the [platform SDK repo](https://github.com/Microsoft/botframework-sdk). We will continue to support and offer maintenance updates via this repo.
 
From now on, https://github.com/Microsoft/botframework-sdk repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the Bot Framework repo found here:
https://github.com/Microsoft/botframework-sdk/issues

For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework

Thank you.
 
The Bot Framework Team
