### ISSUE TITLE
Migrating existing data to docdb

### ISSUE THREAD

**Issue by amitbend** [Microsoft/BotBuilder-Azure#11]
Hi,
I have a live bot, with some amount of data stored already in the free Microsoft's default storage.
I want to move it to my own docdb, but i don't want all the user to lose their data.

How can i migrate the existing data?

**Comment by amitbend** [comment]
Hey, any update? @msft-shahins

**Comment by msft-shahins** [comment]
@amitbend you are responsible for migrating data yourself. You can do this dynamically, by migrating data whenever a user talks to your bot: 1) load data from default storage, 2) converse with user, 3) save data to doc db when persisting the conversation data bags. Or maintain a list of all user ids and conversation ids that your bot has interacted with and develop a migrations tool that read data from default storage and write to doc db.
