### ISSUE TITLE
Why is maxDataLength hard coded?

### ISSUE THREAD

**Issue by thingista** [microsoft/BotBuilder-Azure#12]
We are moving to the Azure bot storage mechanism instead of the default botBuilder one since the botBuilder's 65kb size limit was a problem for us (we need a bit more). So I migrated everything to this, until I realised it has the exact same size limit and it's hard coded:
[https://github.com/Microsoft/BotBuilder-Azure/blob/master/Node/lib/Consts.js#L3](url)

Is there a reason for this?

**Comment by cleemullins** [comment]
Thank you for opening an issue against the BotBuilder-Azure repo. As part of the Bot Framework v4 release, we’ve moved all the Azure related work to the [platform SDK repo](https://github.com/Microsoft/botframework-sdk). We will continue to support and offer maintenance updates via this repo.
 
From now on, https://github.com/Microsoft/botframework-sdk repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the Bot Framework repo found here:
https://github.com/Microsoft/botframework-sdk/issues

For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework

Thank you.
 
The Bot Framework Team
