### ISSUE TITLE
Slack's 'reaction_added' event is not captured by the bot service

### ISSUE THREAD

**Issue by SunSeaAndPalms** [microsoft/BotBuilder-Azure#13]
I'm not sure if that is proper place for the issue, however I haven't found a specific botservice-slack repo.

My goal is to capture emoji reactions from the slack bot.

I have following code deployed to azure:

```
...
var connector = new azure.BotServiceConnector(...);
var bot = new builder.UniversalBot(connector);
bot.use({
  receive: function (session, next) {
    history.addIncomingMessage(session, next);
  },
  send: function (event, next) {
    history.addOutgoingMessage(event, next);
  }
});
...
```

Then in slack:
- Send message 1
- Receive message 2 from my bot
- React with emoji on the message 2
![image](https://cloud.githubusercontent.com/assets/3924308/26350687/c647db5e-3fbc-11e7-86b9-8f288dee72fe.png)

In my history I see message 1 event and message 2 event, but no emoji event. Seems like bot service slack integration should listen to [reaction_added](https://api.slack.com/events/reaction_added) and [reaction_removed](https://api.slack.com/events/reaction_removed) slack events.

**Comment by cleemullins** [comment]
Thank you for opening an issue against the BotBuilder-Azure repo. As part of the Bot Framework v4 release, we’ve moved all the Azure related work to the [platform SDK repo](https://github.com/Microsoft/botframework-sdk). We will continue to support and offer maintenance updates via this repo.
 
From now on, https://github.com/Microsoft/botframework-sdk repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the Bot Framework repo found here:
https://github.com/Microsoft/botframework-sdk/issues

For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework

Thank you.
 
The Bot Framework Team
