### ISSUE TITLE
Question about encrypting logs in Table Logger

### ISSUE THREAD

**Issue by am071092** [microsoft/BotBuilder-Azure#16]
I am using the TableLogger.cs code to log messages to Table Storage. I am encrypting the activity object using TableEncryptionPolicy:
` TableEncryptionPolicy policy = new TableEncryptionPolicy(EncryptionHelper.Rsa, null);

            _tableRequestOptions = new TableRequestOptions()
            {
                EncryptionResolver = (pk, rk, propName) =>
                {
                    if (propName.StartsWith("Activity"))
                        return true;

                    return false;
                },
                EncryptionPolicy = policy
            };`
Can you please explain why the following code is required in ActivityEntity? Is it because the Activity object can get too big and we need to compress it? 

```
`public override IDictionary<string, EntityProperty> WriteEntity(OperationContext operationContext)
            {
                var props = base.WriteEntity(operationContext);
                var buffer = JsonConvert.SerializeObject(Activity).Compress();
                var start = 0;
                var blockid = 0;
                while (start < buffer.Length)
                {
                    var blockSize = Math.Min(buffer.Length - start, FieldLimit);
                    var block = new byte[blockSize];
                    Array.Copy(buffer, start, block, 0, blockSize);
                    props[$"Activity{blockid++}"] = new EntityProperty(block);
                    start += blockSize;
                }
                return props;
            }`
```

Since, you can only encrypt strings, I have removed the above code. Instead, I am simply serializing the Activity object into string so it can be encrypted.

**Comment by EricDahlvang** [comment]
Hi @ankurMalhotra 

The compression is one thing.  The rest of the code ensures the 64kb size limit for byte array properties is not exceeded: https://docs.microsoft.com/en-us/rest/api/storageservices/understanding-the-table-service-data-model#property-types

**Comment by cleemullins** [comment]
Thank you for opening an issue against the BotBuilder-Azure repo. As part of the Bot Framework v4 release, we’ve moved all the Azure related work to the [platform SDK repo](https://github.com/Microsoft/botframework-sdk). We will continue to support and offer maintenance updates via this repo.
 
From now on, https://github.com/Microsoft/botframework-sdk repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the Bot Framework repo found here:
https://github.com/Microsoft/botframework-sdk/issues

For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework

Thank you.
 
The Bot Framework Team
