### ISSUE TITLE
Update to latest version on botbuilder

### ISSUE THREAD

**Issue by ejadib** [microsoft/BotBuilder-Azure#18]
C# currently depends on 3.5.5 and Node on 3.0.2. This is preventing users using this library to upgrade their bots to the latest version of the sdks.

**Comment by jsiegmund** [comment]
Created a PR, but please look into the testing part.

**Comment by cleemullins** [comment]
Thank you for opening an issue against the BotBuilder-Azure repo. As part of the Bot Framework v4 release, we’ve moved all the Azure related work to the [platform SDK repo](https://github.com/Microsoft/botframework-sdk). We will continue to support and offer maintenance updates via this repo.
 
From now on, https://github.com/Microsoft/botframework-sdk repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the Bot Framework repo found here:
https://github.com/Microsoft/botframework-sdk/issues

For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework

Thank you.
 
The Bot Framework Team
