### ISSUE TITLE
Change references from DocumentDB to CosmosDB

### ISSUE THREAD

**Issue by dandriscoll** [microsoft/BotBuilder-Azure#19]

**Comment by stevengum97** [comment]
For reference regarding Azure's [`documentdb`](https://www.npmjs.com/package/documentdb), the Azure team is not planning on updating the package's name to cosmosdb per @moderakh:

> [Thanks for the question. This repo still provide a SDK for DocumentDB APIs and so we are not planning to change the package name nor the repo name.](https://github.com/Azure/azure-documentdb-node/issues/196#issuecomment-301936790)

**Comment by moderakh** [comment]
@stevengum97 thanks you.

CosmosDB provides multiple APIs: documentdb, mongotb, and table. As the nodejs SDK provide documentdb API for cosmosdb we are not planning to rename the SDK.

**Comment by stevengum97** [comment]
Makes perfect sense to me, thanks for stopping by to provide more details @moderakh! :smiley:

**Comment by cleemullins** [comment]
Thank you for opening an issue against the BotBuilder-Azure repo. As part of the Bot Framework v4 release, we’ve moved all the Azure related work to the [platform SDK repo](https://github.com/Microsoft/botframework-sdk). We will continue to support and offer maintenance updates via this repo.
 
From now on, https://github.com/Microsoft/botframework-sdk repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the Bot Framework repo found here:
https://github.com/Microsoft/botframework-sdk/issues

For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework

Thank you.
 
The Bot Framework Team
