### ISSUE TITLE
Cannot retrieve documents from database

### ISSUE THREAD

**Issue by ricechenghk** [microsoft/BotBuilder-Azure#29]
I am trying to retrieve the documents from database. However, it shows me the following. 
`
TypeError: Cannot read property 'queryDocuments' of undefined

    at DocumentDbClient.retrieve (node_modules/botbuilder-azure/lib/DocumentDbClient.js:45:35)

    at MyBot.send (bot/bot.js:959:26)

    at app.js:57:13
`

**Comment by stevengum97** [comment]
@ricechenghk, can you provide the code for your bot? We'll be able to better assist you if you provide your code.

Which version of `botbuilder-azure` are you using?

Are you using the latest version of the [`botbuilder`](https://www.npmjs.com/package/botbuilder) SDK?

**Comment by cleemullins** [comment]
Thank you for opening an issue against the BotBuilder-Azure repo. As part of the Bot Framework v4 release, we’ve moved all the Azure related work to the [platform SDK repo](https://github.com/Microsoft/botframework-sdk). We will continue to support and offer maintenance updates via this repo.
 
From now on, https://github.com/Microsoft/botframework-sdk repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the Bot Framework repo found here:
https://github.com/Microsoft/botframework-sdk/issues

For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework

Thank you.
 
The Bot Framework Team
