### ISSUE TITLE
Skype: Why fails skype, when I send 12 button 

### ISSUE THREAD

**Issue by Shurpanchik** [microsoft/BotBuilder-Azure#3]
var builder = require("botbuilder");
var botbuilder_azure = require("botbuilder-azure");

var useEmulator = (process.env.NODE_ENV == 'development');

var connector = useEmulator ? new builder.ChatConnector() : new botbuilder_azure.BotServiceConnector({
    appId: process.env['MicrosoftAppId'],
    appPassword: process.env['MicrosoftAppPassword'],
    stateEndpoint: process.env['BotStateEndpoint'],
    openIdMetadata: process.env['BotOpenIdMetadata']
});

var bot = new builder.UniversalBot(connector);
bot.dialog('/', function (session) {
    builder.Prompts.choice(session,"Choose time","09:00|10:00|11:00|12:00|13:00|14:00|15:00|16:00|17:00|18:00|19:00|20:00" , { 
                    listStyle: builder.ListStyle.button,
                });
});

if (useEmulator) {
    var restify = require('restify');
    var server = restify.createServer();
    server.listen(3978, function () {
        console.log('test bot endpont at http://localhost:3978/api/messages');
    });
    server.post('/api/messages', connector.listen());
    
} else {
    module.exports = { default: connector.listen() }   
}

![failskypebot](https://cloud.githubusercontent.com/assets/18235465/22368913/77b5a842-e4a2-11e6-88ff-089007dd0613.png)

**Comment by willportnoy** [comment]
@Shurpanchik I would file this issue on https://github.com/Microsoft/BotBuilder/issues so we can get the attention of the right people.

It seems like more of a skype than azure question?

**Comment by AntipovAndrew** [comment]
@willportnoy When I host on heroku, skype doesn't crash

**Comment by Shurpanchik** [comment]
@willportnoy When I host on heroku, skype doesn't crash

**Comment by cleemullins** [comment]
Thank you for opening an issue against the BotBuilder-Azure repo. As part of the Bot Framework v4 release, we’ve moved all the Azure related work to the [platform SDK repo](https://github.com/Microsoft/botframework-sdk). We will continue to support and offer maintenance updates via this repo.
 
From now on, https://github.com/Microsoft/botframework-sdk repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the Bot Framework repo found here:
https://github.com/Microsoft/botframework-sdk/issues

For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework

Thank you.
 
The Bot Framework Team
