### ISSUE TITLE
documentDb needs updating 

### ISSUE THREAD

**Issue by davidparker** [Microsoft/BotBuilder-Azure#31]
currently I am using 1.18   but unable to run the project because botbilder.azure is dependant on 1.11 that is quite a good few ( more than 10 ) major releases and patches behind.

I don't want to have to downgrade the whole project, just to get table storage logging.  and cant seem to remove the un-needed table storage, as again, the whole thing is stuck on being well behind and dependant.

any idea if this project is still alive and going to be updated?

ta

**Comment by stevengum97** [comment]
@davidparker, thanks for reporting this! Someone will look into it and hopefully we can get an update out soon.

**Comment by stevengum97** [comment]
Created PR #34 to update version dependencies for Node.js extension. Pending .NET extension.

**Comment by EricDahlvang** [comment]
Created PR https://github.com/Microsoft/BotBuilder-Azure/pull/35 to update DocumentDb nuget reference

**Comment by stevengum97** [comment]
@davidparker can you confirm that the updated dependency is working for you?

**Comment by davidparker** [comment]
Hi. I couldn't use it at the time so have my own version that I updated all
the dependencies myself.   Am sure that if your keeping up to date with
everyone else.  Then it will be fine.  But I haven't switched back to using
the original nuget as of yet.    Thanks for been on it though and spread
the word to the other teams as not updating nuget packages for new releases
seems to be a really common thing with Microsoft of late.    Ta.   Dave

**Comment by nwhitmont** [comment]
hi

**Comment by stevengum** [comment]
Closing issue as it was resolved via #34 and #35.
