### ISSUE TITLE
Key generation for private MSTeams conversations can exceed 255 characters

### ISSUE THREAD

**Issue by shepwalker** [microsoft/BotBuilder-Azure#32]
Releated to https://github.com/Microsoft/BotBuilder/issues/3637

I'm currently seeing in a subset of 1:1 conversations to the bot in MSTeams, dialogue fails on an attempt write to state service.  Happy to PR something here but guidance to make this backwards compatible would be appreciated.  
System.Web.HttpException (0x80004005): Message: {"Errors":["The input name 'msteams:private{large key}' is invalid. Ensure to provide a unique non-empty string less than '255' characters.","The request payload is invalid. Ensure to provide a valid request payload."]}

**Comment by cleemullins** [comment]
Thank you for opening an issue against the BotBuilder-Azure repo. As part of the Bot Framework v4 release, we’ve moved all the Azure related work to the [platform SDK repo](https://github.com/Microsoft/botframework-sdk). We will continue to support and offer maintenance updates via this repo.
 
From now on, https://github.com/Microsoft/botframework-sdk repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the Bot Framework repo found here:
https://github.com/Microsoft/botframework-sdk/issues

For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework

Thank you.
 
The Bot Framework Team
