### ISSUE TITLE
Update azure-storage npm dependency

### ISSUE THREAD

**Issue by harshithkashyap** [microsoft/BotBuilder-Azure#37]
The azure storage npm module used by this project is set to [1.3.2](https://github.com/Microsoft/BotBuilder-Azure/blob/master/Node/package.json#L27) which is very old. The current azure table storage version is 2.6.0.

1. Please update the azure-storage npm dependency.
2. [buildTableService()](https://github.com/Microsoft/BotBuilder-Azure/blob/master/Node/src/AzureTableClient.ts#L139-L157) function is called each time an entity is inserted or retrieved. This further calls `azure.createTableService` method from `azure-storage` library. This could be moved to constructor and store tableService as an instance variable (`this.tableService`) instead of creating the tableService object on each execution.

I can submit a PR for this but it'll be internal breaking change as AzureTableClient expects `IStorageError`, `IHttpResponse` and other interfaces as return values which are not compatible with tableService return values types.

**Comment by cleemullins** [comment]
Thank you for opening an issue against the BotBuilder-Azure repo. As part of the Bot Framework v4 release, we’ve moved all the Azure related work to the [platform SDK repo](https://github.com/Microsoft/botframework-sdk). We will continue to support and offer maintenance updates via this repo.
 
From now on, https://github.com/Microsoft/botframework-sdk repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the Bot Framework repo found here:
https://github.com/Microsoft/botframework-sdk/issues

For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework

Thank you.
 
The Bot Framework Team
