### ISSUE TITLE
Missing definitions in botbuilder-azure.d.ts

### ISSUE THREAD

**Issue by brendanarnold** [Microsoft/BotBuilder-Azure#38]
I get the following when installing 3.0.4 ...

> node_modules/botbuilder-azure/lib/botbuilder-azure.d.ts(252,49): error TS2304: Cannot find name 'ConnectionConfig'.
> node_modules/botbuilder-azure/lib/botbuilder-azure.d.ts(259,43): error TS2304: Cannot find name 'ConnectionOptions'.

Do the definitions need updating?

**Comment by kayone** [comment]
I'm having the same issue, any resolution/workarounds for this?

**Comment by Pencroff** [comment]
I temporally fixed by adding `import { ConnectionConfig, ConnectionOptions } from 'tedious';` to top of `botbuilder-azure.d.ts` and it's require setup `npm install --save @types/tedious`

**Comment by carlosscastro** [comment]
Thanks all. We'll look into this.

**Comment by armonge** [comment]
@carlosscastro @stevengum97 any progress on this one?

**Comment by sheerun** [comment]
Any workaround?

**Comment by spontoreau** [comment]
Hi, any update?

**Comment by stevengum97** [comment]
Sorry for the painfully long time it took to get #55 merged... It has finally been merged and there is a new release ([3.1.0](https://www.npmjs.com/package/botbuilder-azure/v/3.1.0)) out.

**Comment by stevengum** [comment]
Closing via #55.
