### ISSUE TITLE
How to save bot chat history ? 

### ISSUE THREAD

**Issue by rjgmail88** [microsoft/BotBuilder-Azure#39]
Hello, 

I am using node js sdk to write ms bot service. Currently, I am saving everything in data bags (conversationData, userData etc) and using documentDb to store the state. I have also implemented middleware logging to intercept user to Bot and bot to user messages and logging them on console. 
There are few concerns with this approach,

1. conversationData is cleared when we call endConversation() in dialog. Thats expected by design but we would like to persist this data for multiple conversation flows with same user (same conversation id.) Now, json document in db gets replaced with new keys on conversationData when user start new intent. 
Ex: schedule a meeting with {name} for {day} at {place}.
we save conversationData.name , conversationData.day , and conversationData. place.

same user starts over schedule a meeting with {name2} for {day2} at {place2}.
documentDb entry gets replaced with conversationData.name1 , conversationData.day2 , and conversationData. place2

Ideally, we would like to keep everything. 

2. Issue 2 is middleware logging is not able to hold session object so I can't save each  event.text to any databag? Is this correct approach or there is better way to save chat history ?

const logUserConversation = (event) => {
    console.log(' ******** BOT/User Message: ' + event.text);
   //Want to save  event.text somewhere ??
};

//Middleware for logging
bot.use({
    receive: function (event, next) {
        logUserConversation(event);
        next();
    },
    send: function (event, next) {
        logUserConversation(event);
        next();
    }
});

Also, I am not sure why ConversationData data bag is cleared even though I set to true as follows for persistence.

**bot.set('persistConversationData', true);**

any help would me much appreciated. Thanks in advance.

**Comment by bora89** [comment]
I am interested in saving chat history too

**Comment by rjgmail88** [comment]
I had create one more thread here https://github.com/Microsoft/BotBuilder/issues/3682

**Comment by terabytes** [comment]
See my answer to this question [here](https://github.com/Microsoft/BotBuilder/issues/3682#issuecomment-360585870)

**Comment by msulaksh** [comment]
@terabytes has interesting solution.

**Comment by cleemullins** [comment]
Thank you for opening an issue against the BotBuilder-Azure repo. As part of the Bot Framework v4 release, we’ve moved all the Azure related work to the [platform SDK repo](https://github.com/Microsoft/botframework-sdk). We will continue to support and offer maintenance updates via this repo.
 
From now on, https://github.com/Microsoft/botframework-sdk repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the Bot Framework repo found here:
https://github.com/Microsoft/botframework-sdk/issues

For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework

Thank you.
 
The Bot Framework Team
