### ISSUE TITLE
Using own mongodb storage server

### ISSUE THREAD

**Issue by bora89** [microsoft/BotBuilder-Azure#43]
Hi guys, thank you for the great lib! But it seems like it can operate only with cloud infrastructure of the Azure, but what if I want to store some data on my own mongodb instance? How can it be implemented?

**Comment by aakashkag** [comment]
try https://github.com/Manacola/msbotframework-mongo-middlelayer

**Comment by cleemullins** [comment]
Thank you for opening an issue against the BotBuilder-Azure repo. As part of the Bot Framework v4 release, we’ve moved all the Azure related work to the [platform SDK repo](https://github.com/Microsoft/botframework-sdk). We will continue to support and offer maintenance updates via this repo.
 
From now on, https://github.com/Microsoft/botframework-sdk repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the Bot Framework repo found here:
https://github.com/Microsoft/botframework-sdk/issues

For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework

Thank you.
 
The Bot Framework Team
