### ISSUE TITLE
no more than one bot in the same bot data store

### ISSUE THREAD

**Issue by NandoMuttley** [microsoft/BotBuilder-Azure#47]
Hi, I need to share the same collection (CosmosDB) as StateClient for more than one bot. 
I experienced that the values into data property of json of UserData are a merge of all bot that share the collection with the BotId of the last bot that write.

Inspecting the DocumentDbBotDataStore.cs code at line 261

```
case BotStoreType.BotUserData:
                    return $"{key.ChannelId}:user{key.UserId.SanitizeForAzureKeys()}";
```

the entity key not include BotId, 
same thing on SqlBotDataStore.cs at line 289
```

case BotStoreType.BotUserData:
                    entity = await query.FirstOrDefaultAsync(d => d.BotStoreType == botStoreType
                                                    && d.ChannelId == key.ChannelId
                                                    && d.UserId == key.UserId);
```

query ignore the BotId.

My idea is to add BotId to EntityKey **:bot{key.BotId}** in order to make it unique across multiple bot.

```
                case BotStoreType.BotUserData:
                    return $"{key.ChannelId}:bot{key.BotId}:user{key.UserId.SanitizeForAzureKeys()}";

```

Other suggestions ?

Thanks

**Comment by artemious7** [comment]
How about using a different table for each bot? For example, Bot1 uses storage table "botdata1", and Bot2 writes to "botdata2" table. I believe there is an easy way of specifying table name to use.

**Comment by cleemullins** [comment]
Thank you for opening an issue against the BotBuilder-Azure repo. As part of the Bot Framework v4 release, we’ve moved all the Azure related work to the [platform SDK repo](https://github.com/Microsoft/botframework-sdk). We will continue to support and offer maintenance updates via this repo.
 
From now on, https://github.com/Microsoft/botframework-sdk repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the Bot Framework repo found here:
https://github.com/Microsoft/botframework-sdk/issues

For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework

Thank you.
 
The Bot Framework Team
