### ISSUE TITLE
[Info] Update documentation, create cosmodb as SQL API.

### ISSUE THREAD

**Issue by rafadorado** [microsoft/BotBuilder-Azure#48]
Hi,

Just want to share a simple error I've had today, hopefully it helps someone. I created the Cosmodb as Azure Table API and I was getting this error:

```
error: failed to initialize azure table client. error: error: error code: 400 error body: {"odata.error":{"code":"badrequest","message":{"lang":"en-us","value":"one of the input values is invalid.
```

Once I created it with SQL API, everything went fine :-)

Cheers

**Comment by cleemullins** [comment]
Thank you for opening an issue against the BotBuilder-Azure repo. As part of the Bot Framework v4 release, we’ve moved all the Azure related work to the [platform SDK repo](https://github.com/Microsoft/botframework-sdk). We will continue to support and offer maintenance updates via this repo.
 
From now on, https://github.com/Microsoft/botframework-sdk repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the Bot Framework repo found here:
https://github.com/Microsoft/botframework-sdk/issues

For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework

Thank you.
 
The Bot Framework Team
