### ISSUE TITLE
storage exception during createifexists every second run of the bot emulator.

### ISSUE THREAD

**Issue by jay2deguzman** [microsoft/BotBuilder-Azure#50]
Hi guys im using TableLogger.cs implementation to log conversation history to azure table storage. At first fire on my bot emulator it will run smoothly but after you stop it and do a rerun, It will encounter a storageexception 409 conflict error. This happens when i stop visual studio and do a rerun on vs and a refresh on bot emulator, then as soon as you type your first message. boom! More details : [https://stackoverflow.com/questions/48395464/tablelogger-cs-throwing-storageexception-409-conflict](Link)

Global Asax:

 ` var tableName = ConfigurationManager.AppSettings["TableName"].ToString();
        var account = CloudStorageAccount.Parse(ConfigurationManager.ConnectionStrings["StorageConnectionString"].ConnectionString);

        //Azure StateData
        Conversation.UpdateContainer(
            builder =>
            {
                //azure botdata
                builder.RegisterModule(new AzureModule(Assembly.GetExecutingAssembly()));
                var store = new TableBotDataStore(ConfigurationManager.ConnectionStrings["StorageConnectionString"].ConnectionString);
                builder.Register(c => store)
                   .Keyed<IBotDataStore<BotData>>(AzureModule.Key_DataStore)
                   .AsSelf()
                   .SingleInstance();
                //azure conversation history
                account.CreateCloudTableClient().GetTableReference(tableName).DeleteIfExists();
                builder.RegisterModule(new TableLoggerModule(account, tableName));
            });
`

**Comment by cleemullins** [comment]
Thank you for opening an issue against the BotBuilder-Azure repo. As part of the Bot Framework v4 release, we’ve moved all the Azure related work to the [platform SDK repo](https://github.com/Microsoft/botframework-sdk). We will continue to support and offer maintenance updates via this repo.
 
From now on, https://github.com/Microsoft/botframework-sdk repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the Bot Framework repo found here:
https://github.com/Microsoft/botframework-sdk/issues

For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework

Thank you.
 
The Bot Framework Team
