### ISSUE TITLE
Adding support to MongoDB

### ISSUE THREAD

**Issue by rafadorado** [microsoft/BotBuilder-Azure#51]
Hi,

This issue is for starting a pull request process. I have a working MongoDb integration that works exactly as DocumentDb client for the Node SDK. I am testing it with CosmosDB with MongoAPI without problems.

## Repo

- Branch mongodbclient
- https://github.com/rafadorado/BotBuilder-Azure/tree/mongodbclient

## MongoClient

https://github.com/rafadorado/BotBuilder-Azure/blob/mongodbclient/Node/src/MongoDbClient.ts

## Test

https://github.com/rafadorado/BotBuilder-Azure/blob/mongodbclient/Node/test/MongoDbClientTest.js

## Example

https://github.com/rafadorado/BotBuilder-Azure/blob/mongodbclient/Node/examples/feature-mongoDb/app.js

## Credit

Credit to @aakashkag for this: https://github.com/Manacola/msbotframework-mongo-middlelayer

**Comment by cleemullins** [comment]
Thank you for opening an issue against the BotBuilder-Azure repo. As part of the Bot Framework v4 release, we’ve moved all the Azure related work to the [platform SDK repo](https://github.com/Microsoft/botframework-sdk). We will continue to support and offer maintenance updates via this repo.
 
From now on, https://github.com/Microsoft/botframework-sdk repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the Bot Framework repo found here:
https://github.com/Microsoft/botframework-sdk/issues

For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework

Thank you.
 
The Bot Framework Team
