### ISSUE TITLE
Some requests to azure storage account yields 404 responses

### ISSUE THREAD

**Issue by Kannaj** [microsoft/BotBuilder-Azure#54]
We're maintaining the bot state in azure storage account (table service)

```
    var azureTableClient = new azure.AzureTableClient(environment.config.BOT.TABLE_NAME, environment.config.BOT.STORAGE_NAME, environment.config.BOT.STORAGE_KEY);

    var tableStorage = new azure.AzureBotStorage({gzipData: false}, azureTableClient);
```

some of the requests to the table however seem to yield 404 responses (despite the values actually being on the table)

here's an example query for the request
```
1.0;2018-02-01T12:45:39.3986312Z;QueryEntity;ClientOtherError;404;98;97;authenticated;prodbotstate;prodbotstate;table;"https://prodbotstate.table.core.windows.net:443/botstate(PartitionKey=%27xxxxxxxx%27,RowKey=%xxxx-xxxx-11e8-xxxx-15d2ff98ccae%27)";"/prodbotstate";
```

I manually tried querying the table using the provided partition key and the value does exist in the table. How can i further debug this to see whats going on?

Thanks

**Comment by dvorakjan** [comment]
Same issue here - 404 status codes for some state table calls in Application Insights.

```
404 https://***.table.core.windows.net:443/StateData(PartitionKey=%***%27,RowKey=%27userData%27)
```

What can be the reason? Can we provide some more information to help solving this issue?

**Comment by fkatada** [comment]
Also experiencing the same issue

![image](https://user-images.githubusercontent.com/13221718/42810689-1b4da8bc-89eb-11e8-9395-03cbbfd98df6.png)

**Comment by cleemullins** [comment]
Thank you for opening an issue against the BotBuilder-Azure repo. As part of the Bot Framework v4 release, we’ve moved all the Azure related work to the [platform SDK repo](https://github.com/Microsoft/botframework-sdk). We will continue to support and offer maintenance updates via this repo.
 
From now on, https://github.com/Microsoft/botframework-sdk repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the Bot Framework repo found here:
https://github.com/Microsoft/botframework-sdk/issues

For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework

Thank you.
 
The Bot Framework Team
