### ISSUE TITLE
Node.js function issues when trying to connect to Azure SQL Database

### ISSUE THREAD

**Issue by c1mak31tra1n** [microsoft/BotBuilder-Azure#59]
Hey everyone,

So for some reason I'm having issues when using the code at the bottom. It will run anything that I place in my first function:

```node.js
 function (session) {
        session.send("Hi there!");
        builder.Prompts.text(session, "What's your name?");   
    },
```

but will not run the function that follows. It will just re-run the first function when it receives an answer to "what's your name?" 

However, if I switch over to table storage on my account or use the in-memory storage, then this will work without any issues. I've even tried running two simple functions like this:

```node.js
 function (session) {
        session.send("Hi there!"); 
    },
 function (session) {
        builder.Prompts.text(session, "What's your name?");   
    },
```

with no success. The table in the database that I'm writing to will capture the initial state of the program (for instance):

```json
{"BotBuilder.Data.SessionState":{"callstack":[{"id":"*:/","state":{"BotBuilder.Data.WaterfallStep":0}},{"id":"BotBuilder:prompt-text","state":{"options":{"prompt":"What's your name?","promptAfterAction":true,"libraryNamespace":"*"},"turns":0,"lastTurn":1111111111111,"isReprompt":false,"name":"umm"}}],"lastAccess":1111111111111,"version":0}}
```
(I replaced the "lastTurn" and "lastAccess" values with 1's because I'm not exactly sure what data they hold)

I'm assuming that it's probably my lack of knowledge regarding how I'm connected to the database that's causing this issue, but I'm completely stuck and haven't been able to find anything via searching. My full code is the following:

```node.js
var restify = require('restify');
var builder = require('botbuilder');
var botbuilder_azure = require("botbuilder-azure");

// Setup Restify Server
var server = restify.createServer();
server.listen(process.env.port || process.env.PORT || 3978, function () {
   console.log('%s listening to %s', server.name, server.url); 
});
  
// Create chat connector for communicating with the Bot Framework Service
var connector = new builder.ChatConnector({
    appId: process.env.MicrosoftAppId,
    appPassword: process.env.MicrosoftAppPassword,
    openIdMetadata: process.env.BotOpenIdMetadata 
});

// Listen for messages from users 
server.post('/api/messages', connector.listen());

var sqlConfig = {
    userName: 'USERNAME',
    password: 'PASSWORD',
    server: 'SERVER_NAME',
    //enforceTable: true, // If this property is not set to true it defaults to false. When false if the specified table is not found, the bot will throw an error.
    options: {
        database: 'DATABASE',
        table: 'TABLE',
        encrypt: true,
        rowCollectionOnRequestCompletion: true
    }
}

var sqlClient = new botbuilder_azure.AzureSqlClient(sqlConfig);
var sqlStorage = new botbuilder_azure.AzureBotStorage({ gzipData: false }, sqlClient);

var bot = new builder.UniversalBot(connector, [
    function (session) {
        session.send("Hi there!");
        builder.Prompts.text(session, "What's your name?");   
    },
    function (session, results) {
       session.userData.name = results.response;
       session.send("Nice to meet you, %s", session.message.text);
       session.send(`Name confirmed: <br/>${session.userData.name}`);
       session.save();
       session.endDialog();
    }
]).set('storage', sqlStorage);
```

**Comment by yashwanthm** [comment]
I think I have a similar issue with connecting to Azure table storage. While the app works fine after deployment, there seems to be an issue with 
`var azureTableClient = new botbuilder_azure.AzureTableClient(tableName, process.env['AzureWebJobsStorage']);`

Where 
`export AzureWebJobsStorage=DefaultEndpointsProtocol=https;AccountName=xxxxxxx;AccountKey=xxxxxxxx;`

Unable to carry out development with the bit because of this issue.

**Comment by yashwanthm** [comment]
@c1mak31tra1n  
Try 
`if(process.env.BotEnv === 'debug'){
    var azureTableClient = new botbuilder_azure.AzureTableClient(tableName, process.env.AccountName, process.env.AccountKey);
}else{
    var azureTableClient = new botbuilder_azure.AzureTableClient(tableName, process.env['AzureWebJobsStorage']);
}`

and on your environment variables, have 
`export AccountName=xxxxxx
export AccountKey=xxxxxx`

This got it working for me.

**Comment by cleemullins** [comment]
Thank you for opening an issue against the BotBuilder-Azure repo. As part of the Bot Framework v4 release, we’ve moved all the Azure related work to the [platform SDK repo](https://github.com/Microsoft/botframework-sdk). We will continue to support and offer maintenance updates via this repo.
 
From now on, https://github.com/Microsoft/botframework-sdk repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the Bot Framework repo found here:
https://github.com/Microsoft/botframework-sdk/issues

For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework

Thank you.
 
The Bot Framework Team
