### ISSUE TITLE
DocumentDbClient requests time out / fail behind a proxy

### ISSUE THREAD

**Issue by kev-slater** [microsoft/BotBuilder-Azure#60]
[DocumentDbClient](https://github.com/Microsoft/BotBuilder-Azure/blob/478790baed4fa675e31b9e71a5038cb5fc376e07/Node/lib/DocumentDbClient.js) requests time out / fail behind a proxy

botbuilder-azure: v3.0.4

Problem is due to the fact that neither the [DocumentDbClient](https://github.com/Microsoft/BotBuilder-Azure/blob/478790baed4fa675e31b9e71a5038cb5fc376e07/Node/lib/DocumentDbClient.js) constructor or initialize() allow a connection policy to be specified. This policy would then be provided when calling the DocumentClient constructor. A connection policy would allow proxy settings to take affect.

**Comment by cleemullins** [comment]
Thank you for opening an issue against the BotBuilder-Azure repo. As part of the Bot Framework v4 release, we’ve moved all the Azure related work to the [platform SDK repo](https://github.com/Microsoft/botframework-sdk). We will continue to support and offer maintenance updates via this repo.
 
From now on, https://github.com/Microsoft/botframework-sdk repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the Bot Framework repo found here:
https://github.com/Microsoft/botframework-sdk/issues

For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework

Thank you.
 
The Bot Framework Team
