### ISSUE TITLE
please add null checking !

### ISSUE THREAD

**Issue by virtualvoid** [microsoft/BotBuilder-Azure#61]
I came across this issue: https://github.com/Microsoft/BotBuilder/issues/4179 also: https://github.com/Microsoft/BotBuilder-Azure/issues/58 which seems to be closed now, but no real solution was provided. However by adding null checking:

here:
https://github.com/Microsoft/BotBuilder-Azure/blob/f9c8a56f94fffca61dff69292259244a3db3a3d4/CSharp/Library/Microsoft.Bot.Builder.Azure/TableBotDataStore.cs#L218

and here:
https://github.com/Microsoft/BotBuilder-Azure/blob/f9c8a56f94fffca61dff69292259244a3db3a3d4/CSharp/Library/Microsoft.Bot.Builder.Azure/SqlBotDataStore.cs#L259

seems to resolve the issue.

edit: null checking on the input byte array

**Comment by virtualvoid** [comment]
I forgot to mention that the bot data table needs to be recreated (dunny exactly why).

**Comment by cleemullins** [comment]
Thank you for opening an issue against the BotBuilder-Azure repo. As part of the Bot Framework v4 release, we’ve moved all the Azure related work to the [platform SDK repo](https://github.com/Microsoft/botframework-sdk). We will continue to support and offer maintenance updates via this repo.
 
From now on, https://github.com/Microsoft/botframework-sdk repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the Bot Framework repo found here:
https://github.com/Microsoft/botframework-sdk/issues

For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework

Thank you.
 
The Bot Framework Team
