### ISSUE TITLE
Azure bot storage: Converting circular structure

### ISSUE THREAD

**Issue by droidpl** [microsoft/BotBuilder-Azure#62]
```
TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at addWrite (D:\home\site\wwwroot\project\node_modules\botbuilder-azure\lib\AzureBotStorage.js:105:33)
    at D:\home\site\wwwroot\project\node_modules\botbuilder-azure\lib\AzureBotStorage.js:117:25
    at tryCallOne (D:\home\site\wwwroot\project\node_modules\promise\lib\core.js:37:12)
    at D:\home\site\wwwroot\future-street\project\promise\lib\core.js:123:15
    at flush (D:\home\site\wwwroot\project\node_modules\asap\raw.js:50:29)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

I have found this on the logs of the server. Cannot give further details more than the stringify seems to convert a structure that is circular. Any idea? Maybe would be nice, if the user tries to store something that is circular to provide a different error explaining something or what is it doing?

**Comment by cleemullins** [comment]
Thank you for opening an issue against the BotBuilder-Azure repo. As part of the Bot Framework v4 release, we’ve moved all the Azure related work to the [platform SDK repo](https://github.com/Microsoft/botframework-sdk). We will continue to support and offer maintenance updates via this repo.
 
From now on, https://github.com/Microsoft/botframework-sdk repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the Bot Framework repo found here:
https://github.com/Microsoft/botframework-sdk/issues

For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework

Thank you.
 
The Bot Framework Team
