### ISSUE TITLE
[Looking for info]DocumentDbBotDataStore causes HTTP 404 responses under normal operating conditions #57

### ISSUE THREAD

**Issue by mcconnellt150** [microsoft/BotBuilder-Azure#65]
Hi All,

when can we expect the fix for the below to make it into the botbuidler sdk?

https://github.com/Microsoft/BotBuilder-Azure/pull/56

DocumentDbBotDataStore causes HTTP 404 responses under normal operating conditions #57

Kind Regards,
Thomas

**Comment by cleemullins** [comment]
Thank you for opening an issue against the BotBuilder-Azure repo. As part of the Bot Framework v4 release, we’ve moved all the Azure related work to the [platform SDK repo](https://github.com/Microsoft/botframework-sdk). We will continue to support and offer maintenance updates via this repo.
 
From now on, https://github.com/Microsoft/botframework-sdk repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the Bot Framework repo found here:
https://github.com/Microsoft/botframework-sdk/issues

For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework

Thank you.
 
The Bot Framework Team
