### ISSUE TITLE
Exception when trying to use SQLExpress

### ISSUE THREAD

**Issue by anupamH99** [microsoft/BotBuilder-Azure#66]
[stacktrace.txt](https://github.com/Microsoft/BotBuilder-Azure/files/1915315/stacktrace.txt)

I am hoping windows authentication in web.config is ok/ or should i use sql username /passwords?

```
<connectionStrings>
    <add name="BotDataContextConnectionString"
      providerName="System.Data.SqlClient"
      connectionString="Data Source=HIDD68201\SQLEXPRESS;Initial Catalog=botstate;Integrated Security=True" />
  </connectionStrings>

```
i have a blank database in sqlexpress called botstate.

Any ideas what could be the exception about?
I have attached the stacktrace here.

**Comment by anupamH99** [comment]
with few tweaks to the connectionString, its now throwing an exception:
 Invalid object name 'dbo.SqlBotDataEntities'.

[stacktrace.txt](https://github.com/Microsoft/BotBuilder-Azure/files/1915418/stacktrace.txt)

**Comment by anupamH99** [comment]
Downgrading BotBuilder-Azure nuget pack from 3.2.5 to 3.2.4 resolved it for me.

**Comment by cleemullins** [comment]
Thank you for opening an issue against the BotBuilder-Azure repo. As part of the Bot Framework v4 release, we’ve moved all the Azure related work to the [platform SDK repo](https://github.com/Microsoft/botframework-sdk). We will continue to support and offer maintenance updates via this repo.
 
From now on, https://github.com/Microsoft/botframework-sdk repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the Bot Framework repo found here:
https://github.com/Microsoft/botframework-sdk/issues

For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework

Thank you.
 
The Bot Framework Team
