### ISSUE TITLE
It is currently not possible to use a CosmosDB partitioned collection as the BotDataStore

### ISSUE THREAD

**Issue by nitinka01** [microsoft/BotBuilder-Azure#67]
When I pass a partitioned collection to the `DocumentDbBotDataStore()` constructor in the BotBuilder-Azure [sample application](https://github.com/Microsoft/BotBuilder-Azure/tree/master/CSharp/Samples/DocumentDb), and run the application, it throws the following CosmosDB exception:

`System.InvalidOperationException: PartitionKey value must be supplied for this operation.` 

This restricts us to the 10 GB storage limitation of a non partitioned CosmosDB collection. Is there any upcoming feature to support a partitioned collection?

**Comment by denalisk** [comment]
Bumping because I'm also interested in this use case, was hoping to use a central cosmos resource for a bot servicing multiple tenants

**Comment by cleemullins** [comment]
Thank you for opening an issue against the BotBuilder-Azure repo. As part of the Bot Framework v4 release, we’ve moved all the Azure related work to the [platform SDK repo](https://github.com/Microsoft/botframework-sdk). We will continue to support and offer maintenance updates via this repo.
 
From now on, https://github.com/Microsoft/botframework-sdk repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the Bot Framework repo found here:
https://github.com/Microsoft/botframework-sdk/issues

For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework

Thank you.
 
The Bot Framework Team
