### ISSUE TITLE
[Question] When does the the state information gets deleted from AzureBotStorage?

### ISSUE THREAD

**Issue by ihachani** [microsoft/BotBuilder-Azure#73]
I am using BotBuilder-Azure to save the user state. I want to know if the saved state information gets deleted after the session closes so I won't have a lot of useless state data in my storage.

**Comment by iMicknl** [comment]
Where do you save the state? As far as a I know all session data will be persisted and not automatically removed, only conversationData and dialogData will be removed automatically.

`userData`, `conversationData`, `dialogData`

**Comment by ihachani** [comment]
I am using `conversationData`. After the conversation ends it should be deleted automatically?

**Comment by OZhurbenko** [comment]
@ihachani are you saving it in the Table Storage?
You can explore it with [Azure Storage Explorer](https://azure.microsoft.com/en-ca/features/storage-explorer/) but `conversationData` gets removed from the tables for me at the end of the conversation.

**Comment by cleemullins** [comment]
Thank you for opening an issue against the BotBuilder-Azure repo. As part of the Bot Framework v4 release, we’ve moved all the Azure related work to the [platform SDK repo](https://github.com/Microsoft/botframework-sdk). We will continue to support and offer maintenance updates via this repo.
 
From now on, https://github.com/Microsoft/botframework-sdk repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the Bot Framework repo found here:
https://github.com/Microsoft/botframework-sdk/issues

For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework

Thank you.
 
The Bot Framework Team
