### ISSUE TITLE
Swallow of original StorageException in TableBotDataStore

### ISSUE THREAD

**Issue by sebastienlambert** [microsoft/BotBuilder-Azure#79]
In LoadAsync() and SaveAsync() , the StorageException is not passed to the HttpException as innerException. The StorageException contains valuable information about the exception that is lost. I wast couple of hours/days trying to find an issue I had recently that would have been spot immediately if i had access to the original StorageException. thanks

**Comment by sebastienlambert** [comment]
the line i'm referring to :
https://github.com/Microsoft/BotBuilder-Azure/blob/6ceed6cff3e75dc9aed986f3012907105c038278/CSharp/Library/Microsoft.Bot.Builder.Azure/TableBotDataStore.cs#L126

**Comment by JasonSowers** [comment]
I have submitted a pull request to do exactly what you are requesting.  Thanks for pointing this out.

**Comment by cleemullins** [comment]
Thank you for opening an issue against the BotBuilder-Azure repo. As part of the Bot Framework v4 release, we’ve moved all the Azure related work to the [platform SDK repo](https://github.com/Microsoft/botframework-sdk). We will continue to support and offer maintenance updates via this repo.
 
From now on, https://github.com/Microsoft/botframework-sdk repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the Bot Framework repo found here:
https://github.com/Microsoft/botframework-sdk/issues

For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework

Thank you.
 
The Bot Framework Team
