### ISSUE TITLE
store chat log in database

### ISSUE THREAD

**Issue by ashay-88** [microsoft/BotBuilder-Azure#8]
Hi,
I saw AzureTable example. my question is little different
I want to save chat log in our database , sql server. 
can any one pls give me idea of how do I achieve so...

This is little urgent. Will be great if anyone can address. 

Thanks..
Ashay

**Comment by ashay-88** [comment]
any update??

**Comment by mzilberman** [comment]
This is a great idea, I will start working on SqlServer component for this feature

**Comment by jusso-dev** [comment]
Doesn't this feature already exist?

https://github.com/Microsoft/BotBuilder-Samples/tree/master/CSharp/core-Middleware

**Comment by EricDahlvang** [comment]
There's a blog post about saving activities in sql server here: https://blog.botframework.com/2017/05/05/Saving-Bot-Actions-On-Azure-Sql-Server/

**Comment by cleemullins** [comment]
Thank you for opening an issue against the BotBuilder-Azure repo. As part of the Bot Framework v4 release, we’ve moved all the Azure related work to the [platform SDK repo](https://github.com/Microsoft/botframework-sdk). We will continue to support and offer maintenance updates via this repo.
 
From now on, https://github.com/Microsoft/botframework-sdk repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the Bot Framework repo found here:
https://github.com/Microsoft/botframework-sdk/issues

For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework

Thank you.
 
The Bot Framework Team
