### ISSUE TITLE
Azure Table Storage GZIP

### ISSUE THREAD

**Issue by etbuilder** [microsoft/BotBuilder-Azure#82]
This is not an issue, just a clarification why GZip was used on Azure Table Storage:

Is there a penalty for save bot data as a string and not Gzip Binary?

**Comment by EricDahlvang** [comment]
The comment on TableLogger states:

> Activities are limited to ~1mb when converted to JSON and compressed.  If an activity is bigger than that, it will be dropped.  If your activities are larger, you either need to preprocess them first or use another implementation.

https://github.com/Microsoft/BotBuilder-Azure/blob/dda8f79d1f9587eadb5075279147ddb42c606556/CSharp/Library/Microsoft.Bot.Builder.Azure/TableLogger.cs#L57

It does seem like it would be a good feature addition to have this be configurable via a constructor parameter.

**Comment by cleemullins** [comment]
Thank you for opening an issue against the BotBuilder-Azure repo. As part of the Bot Framework v4 release, we’ve moved all the Azure related work to the [platform SDK repo](https://github.com/Microsoft/botframework-sdk). We will continue to support and offer maintenance updates via this repo.
 
From now on, https://github.com/Microsoft/botframework-sdk repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the Bot Framework repo found here:
https://github.com/Microsoft/botframework-sdk/issues

For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework

Thank you.
 
The Bot Framework Team
