### ISSUE TITLE
Not able to set up Cosmos State Client in Unit Test Project

### ISSUE THREAD

**Issue by mutanttech** [microsoft/BotBuilder-Azure#92]
I am setting up a Unit Test Solution for my .Net Bot developed using Bot SDK 3.15.3.  The first problem is there are no updates test project examples that correspond to current running SDK.
I am using the DialogTestBase.cs, FiberTestBase.cs and MockConnectorFactory.cs files borrowing from source code. The problem is StateClient which is marked deprecated. 
My first question is if it is okay to avoid the warning and use InMemoryDataStore for Unit Tests. 
Second question is if it is feasible to use any other Data Store say Cosmos and what code changes are to be done for it. Any directions will help.

**Comment by jwiley84** [comment]
Hi @mutanttech! 
While i'm not 100% familiar with Unit Testing, I am very familiar with state and state store! 

The InMemoryDataStore can be used for testing, if you're testing things like dialog flow, and you CAN ignore the warning, but bear in mind that any state changes will NOT be saved after the bot stops running.  Your State Store should be in your global.asax.cs file as follows:

`var store = new InMemoryDataStore();

                // Other storage options
                // var store = new TableBotDataStore("...DataStorageConnectionString..."); // requires Microsoft.BotBuilder.Azure Nuget package 
                // var store = new DocumentDbBotDataStore("cosmos db uri", "cosmos db key"); // requires Microsoft.BotBuilder.Azure Nuget package 

                builder.Register(c => store)
                    .Keyed<IBotDataStore<BotData>>(AzureModule.Key_DataStore)
                    .AsSelf()
                    .SingleInstance();`


If you're doing testing for things like what and how state storage works, then do not use InMemoryDataStore. If you chose not to use InMemoryDataStore and opt to go with other options, [THIS](https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-state-azure-cosmosdb?view=azure-bot-service-3.0) will walk you through setting up state (particularly CosmosDB in this case).

**Comment by cleemullins** [comment]
Thank you for opening an issue against the BotBuilder-Azure repo. As part of the Bot Framework v4 release, we’ve moved all the Azure related work to the [platform SDK repo](https://github.com/Microsoft/botframework-sdk). We will continue to support and offer maintenance updates via this repo.
 
From now on, https://github.com/Microsoft/botframework-sdk repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the Bot Framework repo found here:
https://github.com/Microsoft/botframework-sdk/issues

For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework

Thank you.
 
The Bot Framework Team
